services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_laposta
    restart: unless-stopped
    ports:
      - "3000:3000" # change first port if needed
    command: node /app/index.js
